name: 'TryHackMe Badge Workflow'
author: 'Leo Smith - p4p1'
description: 'Gets your tryhackme badge and updates it on your README'

inputs:
  image_path:
    description: 'Path of the image file you want to update'
    default: './assets/thm_propic.png'
    required: false
  username:
    description: 'Try Hack Me username'
    required: true
  committer_username:
    description: 'username of committing bot'
    default: 'thm-p4p1-bot'
    required: false
  committer_email:
    description: 'email of committing bot'
    default: 'p4p1@thm.bot'
    required: false
  commit_message:
    description: 'message of committing bot'
    default: 'Updated THM profile badge'
    required: false
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true

runs:
  using: node16
  main: dist/index.js
branding:
  icon: 'cloud-lightning'
  color: 'red'
